spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn

security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 900000
    refresh-token-expiration: 2592000000   # 30 days in milliseconds

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
  full-name: ${ADMIN_FULL_NAME}
